services:
  - type: web
    name: kan-news-content-assistant
    env: node
    plan: free
    buildCommand: npm install --prefix client && npm install --prefix server && cd client && npx vite build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false  # This will be set manually in Render dashboard
    disk:
      name: kan-news-content-assistant-disk
      mountPath: /opt/render/project/src/server/uploads
      sizeGB: 1 